/**
 * The single registry of everything that exists on the storefront.
 *
 * Navigation, the footer, the sitemap and the tests all read from here, so a
 * link can never point at a route that has not been built, and the sitemap can
 * never advertise a page whose content is still pending.
 *
 * Source of truth: `docs/LOCKED_DECISIONS.md` (D-03 clean URLs, D-15 no dead
 * controls) and `docs/PROJECT_SPECIFICATION.md` §5.4.
 */

export const siteConfig = {
  name: 'Renvura',
  /** Founder-supplied contact details. Never invent these. */
  phone: '01883-115898',
  phoneHref: 'tel:+8801883115898',
  email: 'hello@renvura.com',
  emailHref: 'mailto:hello@renvura.com',
  location: 'Dhaka, Bangladesh',
  ogImage: '/brand/banner-light.png',
  /** Language declared on <html>. Bangla appears per run, never per page (D-02). */
  htmlLang: 'en',
  openGraphLocale: 'en_GB',
} as const;

/**
 * `phase` records when a route becomes real. Only `built` routes may be linked
 * to or listed anywhere in the UI — this is what mechanically enforces the
 * "no dead links" rule (D-15 / §11.1.1). Later-phase routes are declared here
 * so the structure is visible and reviewable, but they are filtered out of
 * every consumer until the phase that builds them flips them to `built`.
 */
export type RoutePhase = 'built' | 'phase-2' | 'phase-3' | 'phase-4' | 'phase-5' | 'phase-9';

export type SiteRoute = {
  /** Absolute path from the site root, e.g. `/about`. */
  path: string;
  /** Label used in navigation and the footer. English (D-02). */
  label: string;
  phase: RoutePhase;
  /**
   * `false` for pages whose content is still being prepared. Those pages emit
   * `noindex, nofollow` and are excluded from the sitemap.
   */
  indexable: boolean;
  priority: number;
  changeFrequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
  /** Which footer column the route belongs to, when it appears in the footer. */
  footerColumn?: 'shop' | 'help' | 'company';
  /** Shown in the header's primary navigation. */
  inHeaderNav?: boolean;
};

export const siteRoutes: readonly SiteRoute[] = [
  // --- Built in Phase 1 -----------------------------------------------------
  {
    path: '/',
    label: 'Home',
    phase: 'built',
    indexable: true,
    priority: 1,
    changeFrequency: 'weekly',
    inHeaderNav: true,
  },
  {
    path: '/about',
    label: 'About',
    phase: 'built',
    indexable: true,
    priority: 0.8,
    changeFrequency: 'monthly',
    footerColumn: 'company',
    inHeaderNav: true,
  },
  {
    path: '/contact',
    label: 'Contact',
    phase: 'built',
    indexable: true,
    priority: 0.7,
    changeFrequency: 'yearly',
    footerColumn: 'help',
    inHeaderNav: true,
  },
  // Content pending — real wording required before these are indexed (D-12).
  {
    path: '/faq',
    label: 'FAQ',
    phase: 'built',
    indexable: false,
    priority: 0.3,
    changeFrequency: 'yearly',
    footerColumn: 'help',
    inHeaderNav: true,
  },
  {
    path: '/shipping',
    label: 'Shipping & Delivery',
    phase: 'built',
    indexable: false,
    priority: 0.3,
    changeFrequency: 'yearly',
    footerColumn: 'help',
  },
  {
    path: '/returns',
    label: 'Returns & Refunds',
    phase: 'built',
    indexable: false,
    priority: 0.3,
    changeFrequency: 'yearly',
    footerColumn: 'help',
  },
  {
    path: '/child-safety',
    label: 'Child Safety',
    phase: 'built',
    indexable: false,
    priority: 0.3,
    changeFrequency: 'yearly',
    footerColumn: 'company',
  },
  {
    path: '/privacy',
    label: 'Privacy Policy',
    phase: 'built',
    indexable: false,
    priority: 0.3,
    changeFrequency: 'yearly',
  },
  {
    path: '/terms',
    label: 'Terms & Conditions',
    phase: 'built',
    indexable: false,
    priority: 0.3,
    changeFrequency: 'yearly',
  },

  // --- Declared, not yet built ---------------------------------------------
  // These are filtered out of navigation, the footer and the sitemap until the
  // phase that builds them changes `phase` to 'built'. Listing them here keeps
  // the commerce structure reviewable without shipping a dead link.
  // Built in Phase 2C. `indexable: false` while the catalogue is still being
  // prepared — an empty shop, or one showing protected demo records, must not
  // be what a search engine sees (D-12, D-08). Flips to true with real products.
  { path: '/products', label: 'All Products', phase: 'built', indexable: false, priority: 0.9, changeFrequency: 'daily', footerColumn: 'shop' },
  { path: '/collections', label: 'Collections', phase: 'phase-2', indexable: true, priority: 0.7, changeFrequency: 'weekly', footerColumn: 'shop' },
  // Built in Phase 3. Never indexable: a search-results URL is generated by a
  // customer, not authored, and letting crawlers mint one page per query is the
  // classic thin-content trap.
  { path: '/search', label: 'Search', phase: 'built', indexable: false, priority: 0.3, changeFrequency: 'weekly' },
  { path: '/offers', label: 'Offers', phase: 'phase-3', indexable: true, priority: 0.7, changeFrequency: 'weekly', footerColumn: 'shop' },
  { path: '/cart', label: 'Cart', phase: 'built', indexable: false, priority: 0.3, changeFrequency: 'weekly' },
  { path: '/checkout', label: 'Checkout', phase: 'built', indexable: false, priority: 0.3, changeFrequency: 'weekly' },
  { path: '/track', label: 'Track Order', phase: 'built', indexable: true, priority: 0.6, changeFrequency: 'monthly', footerColumn: 'help' },
  { path: '/wishlist', label: 'Wishlist', phase: 'phase-4', indexable: false, priority: 0.3, changeFrequency: 'weekly' },
  { path: '/account', label: 'Account', phase: 'phase-5', indexable: false, priority: 0.3, changeFrequency: 'monthly' },
  { path: '/blog', label: 'Articles', phase: 'phase-9', indexable: true, priority: 0.7, changeFrequency: 'weekly', footerColumn: 'company' },
];

/** Only routes that actually exist right now. Everything else is invisible. */
export const builtRoutes: readonly SiteRoute[] = siteRoutes.filter(
  (route) => route.phase === 'built',
);

/** Header primary navigation, in registry order. */
export const headerNavRoutes = builtRoutes.filter((route) => route.inHeaderNav === true);

/** Footer columns, built from the registry so a column can never list a dead link. */
export const footerColumns = [
  { key: 'shop', heading: 'Shop' },
  { key: 'help', heading: 'Help' },
  { key: 'company', heading: 'Company' },
] as const;

export type FooterColumnKey = (typeof footerColumns)[number]['key'];

export function footerRoutesFor(column: FooterColumnKey) {
  return builtRoutes.filter((route) => route.footerColumn === column);
}

/** The five legal/policy routes, for the footer's bottom bar. */
export const policyRoutes = builtRoutes.filter((route) =>
  ['/privacy', '/returns', '/shipping', '/terms', '/child-safety'].includes(route.path),
);

/** Only built *and* indexable routes reach the sitemap. */
export const sitemapRoutes = builtRoutes.filter((route) => route.indexable);

export function isIndexable(path: string): boolean {
  return builtRoutes.some((route) => route.path === path && route.indexable);
}

export function isBuilt(path: string): boolean {
  return builtRoutes.some((route) => route.path === path);
}
