/**
 * Bangladesh administrative locations — division -> district -> upazila.
 *
 * Shipping address collection is a dependent three-level select (section 5, 7.7):
 * choosing a division scopes the district options to it, and choosing a
 * district scopes the upazila options to it. The same dataset drives both the
 * client option lists and the server validation (`isValidLocationHierarchy`),
 * so the two cannot drift apart -- there is one canonical source, not a UI
 * copy and a server copy.
 *
 * **Source and accuracy.** Sourced from the widely-used `bd_geo_code` dataset
 * (github.com/nuhil/bangladesh-geocode), itself derived from Bangladesh
 * National Portal data: 8 divisions, 64 districts, 494 upazilas. A small,
 * deliberate set of names was updated to the current official English
 * spelling where the source still carried a pre-2018-gazette name
 * (division-level "Chattagram" -> "Chattogram", matching the district level
 * which the source already had current; "Barisal" -> "Barishal"; "Comilla" ->
 * "Cumilla"; "Coxsbazar" -> "Cox's Bazar" -- applied consistently at every
 * level, including the affected Sadar upazilas). Nothing else was altered,
 * added or guessed -- this is public administrative geography, not
 * founder-approved business data, but it must still be accurate rather than
 * invented (D-12's spirit applies even where the letter is about business
 * claims).
 *
 * District and division names are each globally unique. **Upazila names are
 * not** -- nine names (e.g. "Kaliganj") recur across different districts, so
 * upazila identity for lookups is always the (district, name) pair, never the
 * name alone; `slug` is namespaced by district for exactly this reason.
 *
 * This stays a local, generated, versioned dataset rather than a runtime
 * dependency or a live API call during checkout (section 5) -- no new package
 * earns its weight for eight divisions worth of static reference data.
 *
 * **One deliberate addition on top of the source data: a "Dhaka City" entry
 * under the Dhaka district's upazilas.** The source dataset stops at upazila
 * granularity, and Dhaka's five upazilas (Savar, Dhamrai, Keraniganj,
 * Nawabganj, Dohar) are its outlying, semi-rural areas -- the city core
 * itself (Dhaka North + South City Corporation) is administered through
 * thanas, a different, finer level the source has no entries for at all. Left
 * as-is, a customer who actually lives in central Dhaka would have had no
 * upazila to select. "Dhaka City" is added as a normal upazila-shaped entry
 * (same shape, same lookup functions, no special-casing anywhere else) so
 * that gap is filled with one clearly-named, real, commonly-used designation
 * -- not dozens of invented or guessed thana entries, which the delivery
 * pricing decision (a flat Dhaka-City-vs-elsewhere split, not a thana-by-thana
 * one) does not need. See `@/lib/checkout/delivery` for where this becomes
 * the delivery-pricing classification.
 */

export type LocationOption = { name: string; slug: string };
export type District = LocationOption & { divisionSlug: string };
export type Upazila = LocationOption & { districtSlug: string };

export const DIVISIONS: readonly LocationOption[] = [
  { name: 'Chattogram', slug: 'chattogram' },
  { name: 'Rajshahi', slug: 'rajshahi' },
  { name: 'Khulna', slug: 'khulna' },
  { name: 'Barishal', slug: 'barishal' },
  { name: 'Sylhet', slug: 'sylhet' },
  { name: 'Dhaka', slug: 'dhaka' },
  { name: 'Rangpur', slug: 'rangpur' },
  { name: 'Mymensingh', slug: 'mymensingh' },
];

export const DISTRICTS: readonly District[] = [
  { name: 'Cumilla', slug: 'cumilla', divisionSlug: 'chattogram' },
  { name: 'Feni', slug: 'feni', divisionSlug: 'chattogram' },
  { name: 'Brahmanbaria', slug: 'brahmanbaria', divisionSlug: 'chattogram' },
  { name: 'Rangamati', slug: 'rangamati', divisionSlug: 'chattogram' },
  { name: 'Noakhali', slug: 'noakhali', divisionSlug: 'chattogram' },
  { name: 'Chandpur', slug: 'chandpur', divisionSlug: 'chattogram' },
  { name: 'Lakshmipur', slug: 'lakshmipur', divisionSlug: 'chattogram' },
  { name: 'Chattogram', slug: 'chattogram', divisionSlug: 'chattogram' },
  { name: 'Cox\'s Bazar', slug: 'coxs-bazar', divisionSlug: 'chattogram' },
  { name: 'Khagrachhari', slug: 'khagrachhari', divisionSlug: 'chattogram' },
  { name: 'Bandarban', slug: 'bandarban', divisionSlug: 'chattogram' },
  { name: 'Sirajganj', slug: 'sirajganj', divisionSlug: 'rajshahi' },
  { name: 'Pabna', slug: 'pabna', divisionSlug: 'rajshahi' },
  { name: 'Bogura', slug: 'bogura', divisionSlug: 'rajshahi' },
  { name: 'Rajshahi', slug: 'rajshahi', divisionSlug: 'rajshahi' },
  { name: 'Natore', slug: 'natore', divisionSlug: 'rajshahi' },
  { name: 'Joypurhat', slug: 'joypurhat', divisionSlug: 'rajshahi' },
  { name: 'Chapainawabganj', slug: 'chapainawabganj', divisionSlug: 'rajshahi' },
  { name: 'Naogaon', slug: 'naogaon', divisionSlug: 'rajshahi' },
  { name: 'Jashore', slug: 'jashore', divisionSlug: 'khulna' },
  { name: 'Satkhira', slug: 'satkhira', divisionSlug: 'khulna' },
  { name: 'Meherpur', slug: 'meherpur', divisionSlug: 'khulna' },
  { name: 'Narail', slug: 'narail', divisionSlug: 'khulna' },
  { name: 'Chuadanga', slug: 'chuadanga', divisionSlug: 'khulna' },
  { name: 'Kushtia', slug: 'kushtia', divisionSlug: 'khulna' },
  { name: 'Magura', slug: 'magura', divisionSlug: 'khulna' },
  { name: 'Khulna', slug: 'khulna', divisionSlug: 'khulna' },
  { name: 'Bagerhat', slug: 'bagerhat', divisionSlug: 'khulna' },
  { name: 'Jhenaidah', slug: 'jhenaidah', divisionSlug: 'khulna' },
  { name: 'Jhalakathi', slug: 'jhalakathi', divisionSlug: 'barishal' },
  { name: 'Patuakhali', slug: 'patuakhali', divisionSlug: 'barishal' },
  { name: 'Pirojpur', slug: 'pirojpur', divisionSlug: 'barishal' },
  { name: 'Barishal', slug: 'barishal', divisionSlug: 'barishal' },
  { name: 'Bhola', slug: 'bhola', divisionSlug: 'barishal' },
  { name: 'Barguna', slug: 'barguna', divisionSlug: 'barishal' },
  { name: 'Sylhet', slug: 'sylhet', divisionSlug: 'sylhet' },
  { name: 'Moulvibazar', slug: 'moulvibazar', divisionSlug: 'sylhet' },
  { name: 'Habiganj', slug: 'habiganj', divisionSlug: 'sylhet' },
  { name: 'Sunamganj', slug: 'sunamganj', divisionSlug: 'sylhet' },
  { name: 'Narsingdi', slug: 'narsingdi', divisionSlug: 'dhaka' },
  { name: 'Gazipur', slug: 'gazipur', divisionSlug: 'dhaka' },
  { name: 'Shariatpur', slug: 'shariatpur', divisionSlug: 'dhaka' },
  { name: 'Narayanganj', slug: 'narayanganj', divisionSlug: 'dhaka' },
  { name: 'Tangail', slug: 'tangail', divisionSlug: 'dhaka' },
  { name: 'Kishoreganj', slug: 'kishoreganj', divisionSlug: 'dhaka' },
  { name: 'Manikganj', slug: 'manikganj', divisionSlug: 'dhaka' },
  { name: 'Dhaka', slug: 'dhaka', divisionSlug: 'dhaka' },
  { name: 'Munshiganj', slug: 'munshiganj', divisionSlug: 'dhaka' },
  { name: 'Rajbari', slug: 'rajbari', divisionSlug: 'dhaka' },
  { name: 'Madaripur', slug: 'madaripur', divisionSlug: 'dhaka' },
  { name: 'Gopalganj', slug: 'gopalganj', divisionSlug: 'dhaka' },
  { name: 'Faridpur', slug: 'faridpur', divisionSlug: 'dhaka' },
  { name: 'Panchagarh', slug: 'panchagarh', divisionSlug: 'rangpur' },
  { name: 'Dinajpur', slug: 'dinajpur', divisionSlug: 'rangpur' },
  { name: 'Lalmonirhat', slug: 'lalmonirhat', divisionSlug: 'rangpur' },
  { name: 'Nilphamari', slug: 'nilphamari', divisionSlug: 'rangpur' },
  { name: 'Gaibandha', slug: 'gaibandha', divisionSlug: 'rangpur' },
  { name: 'Thakurgaon', slug: 'thakurgaon', divisionSlug: 'rangpur' },
  { name: 'Rangpur', slug: 'rangpur', divisionSlug: 'rangpur' },
  { name: 'Kurigram', slug: 'kurigram', divisionSlug: 'rangpur' },
  { name: 'Sherpur', slug: 'sherpur', divisionSlug: 'mymensingh' },
  { name: 'Mymensingh', slug: 'mymensingh', divisionSlug: 'mymensingh' },
  { name: 'Jamalpur', slug: 'jamalpur', divisionSlug: 'mymensingh' },
  { name: 'Netrokona', slug: 'netrokona', divisionSlug: 'mymensingh' },
];

export const UPAZILAS: readonly Upazila[] = [
  { name: 'Debidwar', slug: 'cumilla--debidwar', districtSlug: 'cumilla' },
  { name: 'Barura', slug: 'cumilla--barura', districtSlug: 'cumilla' },
  { name: 'Brahmanpara', slug: 'cumilla--brahmanpara', districtSlug: 'cumilla' },
  { name: 'Chandina', slug: 'cumilla--chandina', districtSlug: 'cumilla' },
  { name: 'Chauddagram', slug: 'cumilla--chauddagram', districtSlug: 'cumilla' },
  { name: 'Daudkandi', slug: 'cumilla--daudkandi', districtSlug: 'cumilla' },
  { name: 'Homna', slug: 'cumilla--homna', districtSlug: 'cumilla' },
  { name: 'Laksam', slug: 'cumilla--laksam', districtSlug: 'cumilla' },
  { name: 'Muradnagar', slug: 'cumilla--muradnagar', districtSlug: 'cumilla' },
  { name: 'Nangalkot', slug: 'cumilla--nangalkot', districtSlug: 'cumilla' },
  { name: 'Cumilla Sadar', slug: 'cumilla--cumilla-sadar', districtSlug: 'cumilla' },
  { name: 'Meghna', slug: 'cumilla--meghna', districtSlug: 'cumilla' },
  { name: 'Monohargonj', slug: 'cumilla--monohargonj', districtSlug: 'cumilla' },
  { name: 'Sadarsouth', slug: 'cumilla--sadarsouth', districtSlug: 'cumilla' },
  { name: 'Titas', slug: 'cumilla--titas', districtSlug: 'cumilla' },
  { name: 'Burichang', slug: 'cumilla--burichang', districtSlug: 'cumilla' },
  { name: 'Lalmai', slug: 'cumilla--lalmai', districtSlug: 'cumilla' },
  { name: 'Chhagalnaiya', slug: 'feni--chhagalnaiya', districtSlug: 'feni' },
  { name: 'Feni Sadar', slug: 'feni--feni-sadar', districtSlug: 'feni' },
  { name: 'Sonagazi', slug: 'feni--sonagazi', districtSlug: 'feni' },
  { name: 'Fulgazi', slug: 'feni--fulgazi', districtSlug: 'feni' },
  { name: 'Parshuram', slug: 'feni--parshuram', districtSlug: 'feni' },
  { name: 'Daganbhuiyan', slug: 'feni--daganbhuiyan', districtSlug: 'feni' },
  { name: 'Brahmanbaria Sadar', slug: 'brahmanbaria--brahmanbaria-sadar', districtSlug: 'brahmanbaria' },
  { name: 'Kasba', slug: 'brahmanbaria--kasba', districtSlug: 'brahmanbaria' },
  { name: 'Nasirnagar', slug: 'brahmanbaria--nasirnagar', districtSlug: 'brahmanbaria' },
  { name: 'Sarail', slug: 'brahmanbaria--sarail', districtSlug: 'brahmanbaria' },
  { name: 'Ashuganj', slug: 'brahmanbaria--ashuganj', districtSlug: 'brahmanbaria' },
  { name: 'Akhaura', slug: 'brahmanbaria--akhaura', districtSlug: 'brahmanbaria' },
  { name: 'Nabinagar', slug: 'brahmanbaria--nabinagar', districtSlug: 'brahmanbaria' },
  { name: 'Bancharampur', slug: 'brahmanbaria--bancharampur', districtSlug: 'brahmanbaria' },
  { name: 'Bijoynagar', slug: 'brahmanbaria--bijoynagar', districtSlug: 'brahmanbaria' },
  { name: 'Rangamati Sadar', slug: 'rangamati--rangamati-sadar', districtSlug: 'rangamati' },
  { name: 'Kaptai', slug: 'rangamati--kaptai', districtSlug: 'rangamati' },
  { name: 'Kawkhali', slug: 'rangamati--kawkhali', districtSlug: 'rangamati' },
  { name: 'Baghaichari', slug: 'rangamati--baghaichari', districtSlug: 'rangamati' },
  { name: 'Barkal', slug: 'rangamati--barkal', districtSlug: 'rangamati' },
  { name: 'Langadu', slug: 'rangamati--langadu', districtSlug: 'rangamati' },
  { name: 'Rajasthali', slug: 'rangamati--rajasthali', districtSlug: 'rangamati' },
  { name: 'Belaichari', slug: 'rangamati--belaichari', districtSlug: 'rangamati' },
  { name: 'Juraichari', slug: 'rangamati--juraichari', districtSlug: 'rangamati' },
  { name: 'Naniarchar', slug: 'rangamati--naniarchar', districtSlug: 'rangamati' },
  { name: 'Noakhali Sadar', slug: 'noakhali--noakhali-sadar', districtSlug: 'noakhali' },
  { name: 'Companiganj', slug: 'noakhali--companiganj', districtSlug: 'noakhali' },
  { name: 'Begumganj', slug: 'noakhali--begumganj', districtSlug: 'noakhali' },
  { name: 'Hatia', slug: 'noakhali--hatia', districtSlug: 'noakhali' },
  { name: 'Subarnachar', slug: 'noakhali--subarnachar', districtSlug: 'noakhali' },
  { name: 'Kabirhat', slug: 'noakhali--kabirhat', districtSlug: 'noakhali' },
  { name: 'Senbug', slug: 'noakhali--senbug', districtSlug: 'noakhali' },
  { name: 'Chatkhil', slug: 'noakhali--chatkhil', districtSlug: 'noakhali' },
  { name: 'Sonaimori', slug: 'noakhali--sonaimori', districtSlug: 'noakhali' },
  { name: 'Haimchar', slug: 'chandpur--haimchar', districtSlug: 'chandpur' },
  { name: 'Kachua', slug: 'chandpur--kachua', districtSlug: 'chandpur' },
  { name: 'Shahrasti', slug: 'chandpur--shahrasti', districtSlug: 'chandpur' },
  { name: 'Chandpur Sadar', slug: 'chandpur--chandpur-sadar', districtSlug: 'chandpur' },
  { name: 'Matlab South', slug: 'chandpur--matlab-south', districtSlug: 'chandpur' },
  { name: 'Hajiganj', slug: 'chandpur--hajiganj', districtSlug: 'chandpur' },
  { name: 'Matlab North', slug: 'chandpur--matlab-north', districtSlug: 'chandpur' },
  { name: 'Faridgonj', slug: 'chandpur--faridgonj', districtSlug: 'chandpur' },
  { name: 'Lakshmipur Sadar', slug: 'lakshmipur--lakshmipur-sadar', districtSlug: 'lakshmipur' },
  { name: 'Kamalnagar', slug: 'lakshmipur--kamalnagar', districtSlug: 'lakshmipur' },
  { name: 'Raipur', slug: 'lakshmipur--raipur', districtSlug: 'lakshmipur' },
  { name: 'Ramgati', slug: 'lakshmipur--ramgati', districtSlug: 'lakshmipur' },
  { name: 'Ramganj', slug: 'lakshmipur--ramganj', districtSlug: 'lakshmipur' },
  { name: 'Rangunia', slug: 'chattogram--rangunia', districtSlug: 'chattogram' },
  { name: 'Sitakunda', slug: 'chattogram--sitakunda', districtSlug: 'chattogram' },
  { name: 'Mirsharai', slug: 'chattogram--mirsharai', districtSlug: 'chattogram' },
  { name: 'Patiya', slug: 'chattogram--patiya', districtSlug: 'chattogram' },
  { name: 'Sandwip', slug: 'chattogram--sandwip', districtSlug: 'chattogram' },
  { name: 'Banshkhali', slug: 'chattogram--banshkhali', districtSlug: 'chattogram' },
  { name: 'Boalkhali', slug: 'chattogram--boalkhali', districtSlug: 'chattogram' },
  { name: 'Anwara', slug: 'chattogram--anwara', districtSlug: 'chattogram' },
  { name: 'Chandanaish', slug: 'chattogram--chandanaish', districtSlug: 'chattogram' },
  { name: 'Satkania', slug: 'chattogram--satkania', districtSlug: 'chattogram' },
  { name: 'Lohagara', slug: 'chattogram--lohagara', districtSlug: 'chattogram' },
  { name: 'Hathazari', slug: 'chattogram--hathazari', districtSlug: 'chattogram' },
  { name: 'Fatikchhari', slug: 'chattogram--fatikchhari', districtSlug: 'chattogram' },
  { name: 'Raozan', slug: 'chattogram--raozan', districtSlug: 'chattogram' },
  { name: 'Karnafuli', slug: 'chattogram--karnafuli', districtSlug: 'chattogram' },
  { name: 'Cox\'s Bazar Sadar', slug: 'coxs-bazar--coxs-bazar-sadar', districtSlug: 'coxs-bazar' },
  { name: 'Chakaria', slug: 'coxs-bazar--chakaria', districtSlug: 'coxs-bazar' },
  { name: 'Kutubdia', slug: 'coxs-bazar--kutubdia', districtSlug: 'coxs-bazar' },
  { name: 'Ukhiya', slug: 'coxs-bazar--ukhiya', districtSlug: 'coxs-bazar' },
  { name: 'Moheshkhali', slug: 'coxs-bazar--moheshkhali', districtSlug: 'coxs-bazar' },
  { name: 'Pekua', slug: 'coxs-bazar--pekua', districtSlug: 'coxs-bazar' },
  { name: 'Ramu', slug: 'coxs-bazar--ramu', districtSlug: 'coxs-bazar' },
  { name: 'Teknaf', slug: 'coxs-bazar--teknaf', districtSlug: 'coxs-bazar' },
  { name: 'Khagrachhari Sadar', slug: 'khagrachhari--khagrachhari-sadar', districtSlug: 'khagrachhari' },
  { name: 'Dighinala', slug: 'khagrachhari--dighinala', districtSlug: 'khagrachhari' },
  { name: 'Panchari', slug: 'khagrachhari--panchari', districtSlug: 'khagrachhari' },
  { name: 'Laxmichhari', slug: 'khagrachhari--laxmichhari', districtSlug: 'khagrachhari' },
  { name: 'Mohalchari', slug: 'khagrachhari--mohalchari', districtSlug: 'khagrachhari' },
  { name: 'Manikchari', slug: 'khagrachhari--manikchari', districtSlug: 'khagrachhari' },
  { name: 'Ramgarh', slug: 'khagrachhari--ramgarh', districtSlug: 'khagrachhari' },
  { name: 'Matiranga', slug: 'khagrachhari--matiranga', districtSlug: 'khagrachhari' },
  { name: 'Guimara', slug: 'khagrachhari--guimara', districtSlug: 'khagrachhari' },
  { name: 'Bandarban Sadar', slug: 'bandarban--bandarban-sadar', districtSlug: 'bandarban' },
  { name: 'Alikadam', slug: 'bandarban--alikadam', districtSlug: 'bandarban' },
  { name: 'Naikhongchhari', slug: 'bandarban--naikhongchhari', districtSlug: 'bandarban' },
  { name: 'Rowangchhari', slug: 'bandarban--rowangchhari', districtSlug: 'bandarban' },
  { name: 'Lama', slug: 'bandarban--lama', districtSlug: 'bandarban' },
  { name: 'Ruma', slug: 'bandarban--ruma', districtSlug: 'bandarban' },
  { name: 'Thanchi', slug: 'bandarban--thanchi', districtSlug: 'bandarban' },
  { name: 'Belkuchi', slug: 'sirajganj--belkuchi', districtSlug: 'sirajganj' },
  { name: 'Chauhali', slug: 'sirajganj--chauhali', districtSlug: 'sirajganj' },
  { name: 'Kamarkhand', slug: 'sirajganj--kamarkhand', districtSlug: 'sirajganj' },
  { name: 'Kazipur', slug: 'sirajganj--kazipur', districtSlug: 'sirajganj' },
  { name: 'Raigonj', slug: 'sirajganj--raigonj', districtSlug: 'sirajganj' },
  { name: 'Shahjadpur', slug: 'sirajganj--shahjadpur', districtSlug: 'sirajganj' },
  { name: 'Sirajganj Sadar', slug: 'sirajganj--sirajganj-sadar', districtSlug: 'sirajganj' },
  { name: 'Tarash', slug: 'sirajganj--tarash', districtSlug: 'sirajganj' },
  { name: 'Ullapara', slug: 'sirajganj--ullapara', districtSlug: 'sirajganj' },
  { name: 'Sujanagar', slug: 'pabna--sujanagar', districtSlug: 'pabna' },
  { name: 'Ishurdi', slug: 'pabna--ishurdi', districtSlug: 'pabna' },
  { name: 'Bhangura', slug: 'pabna--bhangura', districtSlug: 'pabna' },
  { name: 'Pabna Sadar', slug: 'pabna--pabna-sadar', districtSlug: 'pabna' },
  { name: 'Bera', slug: 'pabna--bera', districtSlug: 'pabna' },
  { name: 'Atghoria', slug: 'pabna--atghoria', districtSlug: 'pabna' },
  { name: 'Chatmohar', slug: 'pabna--chatmohar', districtSlug: 'pabna' },
  { name: 'Santhia', slug: 'pabna--santhia', districtSlug: 'pabna' },
  { name: 'Faridpur', slug: 'pabna--faridpur', districtSlug: 'pabna' },
  { name: 'Kahaloo', slug: 'bogura--kahaloo', districtSlug: 'bogura' },
  { name: 'Bogura Sadar', slug: 'bogura--bogura-sadar', districtSlug: 'bogura' },
  { name: 'Shariakandi', slug: 'bogura--shariakandi', districtSlug: 'bogura' },
  { name: 'Shajahanpur', slug: 'bogura--shajahanpur', districtSlug: 'bogura' },
  { name: 'Dupchanchia', slug: 'bogura--dupchanchia', districtSlug: 'bogura' },
  { name: 'Adamdighi', slug: 'bogura--adamdighi', districtSlug: 'bogura' },
  { name: 'Nondigram', slug: 'bogura--nondigram', districtSlug: 'bogura' },
  { name: 'Sonatala', slug: 'bogura--sonatala', districtSlug: 'bogura' },
  { name: 'Dhunot', slug: 'bogura--dhunot', districtSlug: 'bogura' },
  { name: 'Gabtali', slug: 'bogura--gabtali', districtSlug: 'bogura' },
  { name: 'Sherpur', slug: 'bogura--sherpur', districtSlug: 'bogura' },
  { name: 'Shibganj', slug: 'bogura--shibganj', districtSlug: 'bogura' },
  { name: 'Paba', slug: 'rajshahi--paba', districtSlug: 'rajshahi' },
  { name: 'Durgapur', slug: 'rajshahi--durgapur', districtSlug: 'rajshahi' },
  { name: 'Mohonpur', slug: 'rajshahi--mohonpur', districtSlug: 'rajshahi' },
  { name: 'Charghat', slug: 'rajshahi--charghat', districtSlug: 'rajshahi' },
  { name: 'Puthia', slug: 'rajshahi--puthia', districtSlug: 'rajshahi' },
  { name: 'Bagha', slug: 'rajshahi--bagha', districtSlug: 'rajshahi' },
  { name: 'Godagari', slug: 'rajshahi--godagari', districtSlug: 'rajshahi' },
  { name: 'Tanore', slug: 'rajshahi--tanore', districtSlug: 'rajshahi' },
  { name: 'Bagmara', slug: 'rajshahi--bagmara', districtSlug: 'rajshahi' },
  { name: 'Natore Sadar', slug: 'natore--natore-sadar', districtSlug: 'natore' },
  { name: 'Singra', slug: 'natore--singra', districtSlug: 'natore' },
  { name: 'Baraigram', slug: 'natore--baraigram', districtSlug: 'natore' },
  { name: 'Bagatipara', slug: 'natore--bagatipara', districtSlug: 'natore' },
  { name: 'Lalpur', slug: 'natore--lalpur', districtSlug: 'natore' },
  { name: 'Gurudaspur', slug: 'natore--gurudaspur', districtSlug: 'natore' },
  { name: 'Naldanga', slug: 'natore--naldanga', districtSlug: 'natore' },
  { name: 'Akkelpur', slug: 'joypurhat--akkelpur', districtSlug: 'joypurhat' },
  { name: 'Kalai', slug: 'joypurhat--kalai', districtSlug: 'joypurhat' },
  { name: 'Khetlal', slug: 'joypurhat--khetlal', districtSlug: 'joypurhat' },
  { name: 'Panchbibi', slug: 'joypurhat--panchbibi', districtSlug: 'joypurhat' },
  { name: 'Joypurhat Sadar', slug: 'joypurhat--joypurhat-sadar', districtSlug: 'joypurhat' },
  { name: 'Chapainawabganj Sadar', slug: 'chapainawabganj--chapainawabganj-sadar', districtSlug: 'chapainawabganj' },
  { name: 'Gomostapur', slug: 'chapainawabganj--gomostapur', districtSlug: 'chapainawabganj' },
  { name: 'Nachol', slug: 'chapainawabganj--nachol', districtSlug: 'chapainawabganj' },
  { name: 'Bholahat', slug: 'chapainawabganj--bholahat', districtSlug: 'chapainawabganj' },
  { name: 'Shibganj', slug: 'chapainawabganj--shibganj', districtSlug: 'chapainawabganj' },
  { name: 'Mohadevpur', slug: 'naogaon--mohadevpur', districtSlug: 'naogaon' },
  { name: 'Badalgachi', slug: 'naogaon--badalgachi', districtSlug: 'naogaon' },
  { name: 'Patnitala', slug: 'naogaon--patnitala', districtSlug: 'naogaon' },
  { name: 'Dhamoirhat', slug: 'naogaon--dhamoirhat', districtSlug: 'naogaon' },
  { name: 'Niamatpur', slug: 'naogaon--niamatpur', districtSlug: 'naogaon' },
  { name: 'Manda', slug: 'naogaon--manda', districtSlug: 'naogaon' },
  { name: 'Atrai', slug: 'naogaon--atrai', districtSlug: 'naogaon' },
  { name: 'Raninagar', slug: 'naogaon--raninagar', districtSlug: 'naogaon' },
  { name: 'Naogaon Sadar', slug: 'naogaon--naogaon-sadar', districtSlug: 'naogaon' },
  { name: 'Porsha', slug: 'naogaon--porsha', districtSlug: 'naogaon' },
  { name: 'Sapahar', slug: 'naogaon--sapahar', districtSlug: 'naogaon' },
  { name: 'Manirampur', slug: 'jashore--manirampur', districtSlug: 'jashore' },
  { name: 'Abhaynagar', slug: 'jashore--abhaynagar', districtSlug: 'jashore' },
  { name: 'Bagherpara', slug: 'jashore--bagherpara', districtSlug: 'jashore' },
  { name: 'Chougachha', slug: 'jashore--chougachha', districtSlug: 'jashore' },
  { name: 'Jhikargacha', slug: 'jashore--jhikargacha', districtSlug: 'jashore' },
  { name: 'Keshabpur', slug: 'jashore--keshabpur', districtSlug: 'jashore' },
  { name: 'Jashore Sadar', slug: 'jashore--jashore-sadar', districtSlug: 'jashore' },
  { name: 'Sharsha', slug: 'jashore--sharsha', districtSlug: 'jashore' },
  { name: 'Assasuni', slug: 'satkhira--assasuni', districtSlug: 'satkhira' },
  { name: 'Debhata', slug: 'satkhira--debhata', districtSlug: 'satkhira' },
  { name: 'Kalaroa', slug: 'satkhira--kalaroa', districtSlug: 'satkhira' },
  { name: 'Satkhira Sadar', slug: 'satkhira--satkhira-sadar', districtSlug: 'satkhira' },
  { name: 'Shyamnagar', slug: 'satkhira--shyamnagar', districtSlug: 'satkhira' },
  { name: 'Tala', slug: 'satkhira--tala', districtSlug: 'satkhira' },
  { name: 'Kaliganj', slug: 'satkhira--kaliganj', districtSlug: 'satkhira' },
  { name: 'Mujibnagar', slug: 'meherpur--mujibnagar', districtSlug: 'meherpur' },
  { name: 'Meherpur Sadar', slug: 'meherpur--meherpur-sadar', districtSlug: 'meherpur' },
  { name: 'Gangni', slug: 'meherpur--gangni', districtSlug: 'meherpur' },
  { name: 'Narail Sadar', slug: 'narail--narail-sadar', districtSlug: 'narail' },
  { name: 'Lohagara', slug: 'narail--lohagara', districtSlug: 'narail' },
  { name: 'Kalia', slug: 'narail--kalia', districtSlug: 'narail' },
  { name: 'Chuadanga Sadar', slug: 'chuadanga--chuadanga-sadar', districtSlug: 'chuadanga' },
  { name: 'Alamdanga', slug: 'chuadanga--alamdanga', districtSlug: 'chuadanga' },
  { name: 'Damurhuda', slug: 'chuadanga--damurhuda', districtSlug: 'chuadanga' },
  { name: 'Jibannagar', slug: 'chuadanga--jibannagar', districtSlug: 'chuadanga' },
  { name: 'Kushtia Sadar', slug: 'kushtia--kushtia-sadar', districtSlug: 'kushtia' },
  { name: 'Kumarkhali', slug: 'kushtia--kumarkhali', districtSlug: 'kushtia' },
  { name: 'Khoksa', slug: 'kushtia--khoksa', districtSlug: 'kushtia' },
  { name: 'Mirpur', slug: 'kushtia--mirpur', districtSlug: 'kushtia' },
  { name: 'Daulatpur', slug: 'kushtia--daulatpur', districtSlug: 'kushtia' },
  { name: 'Bheramara', slug: 'kushtia--bheramara', districtSlug: 'kushtia' },
  { name: 'Shalikha', slug: 'magura--shalikha', districtSlug: 'magura' },
  { name: 'Sreepur', slug: 'magura--sreepur', districtSlug: 'magura' },
  { name: 'Magura Sadar', slug: 'magura--magura-sadar', districtSlug: 'magura' },
  { name: 'Mohammadpur', slug: 'magura--mohammadpur', districtSlug: 'magura' },
  { name: 'Paikgasa', slug: 'khulna--paikgasa', districtSlug: 'khulna' },
  { name: 'Fultola', slug: 'khulna--fultola', districtSlug: 'khulna' },
  { name: 'Digholia', slug: 'khulna--digholia', districtSlug: 'khulna' },
  { name: 'Rupsha', slug: 'khulna--rupsha', districtSlug: 'khulna' },
  { name: 'Terokhada', slug: 'khulna--terokhada', districtSlug: 'khulna' },
  { name: 'Dumuria', slug: 'khulna--dumuria', districtSlug: 'khulna' },
  { name: 'Botiaghata', slug: 'khulna--botiaghata', districtSlug: 'khulna' },
  { name: 'Dakop', slug: 'khulna--dakop', districtSlug: 'khulna' },
  { name: 'Koyra', slug: 'khulna--koyra', districtSlug: 'khulna' },
  { name: 'Fakirhat', slug: 'bagerhat--fakirhat', districtSlug: 'bagerhat' },
  { name: 'Bagerhat Sadar', slug: 'bagerhat--bagerhat-sadar', districtSlug: 'bagerhat' },
  { name: 'Mollahat', slug: 'bagerhat--mollahat', districtSlug: 'bagerhat' },
  { name: 'Sarankhola', slug: 'bagerhat--sarankhola', districtSlug: 'bagerhat' },
  { name: 'Rampal', slug: 'bagerhat--rampal', districtSlug: 'bagerhat' },
  { name: 'Morrelganj', slug: 'bagerhat--morrelganj', districtSlug: 'bagerhat' },
  { name: 'Kachua', slug: 'bagerhat--kachua', districtSlug: 'bagerhat' },
  { name: 'Mongla', slug: 'bagerhat--mongla', districtSlug: 'bagerhat' },
  { name: 'Chitalmari', slug: 'bagerhat--chitalmari', districtSlug: 'bagerhat' },
  { name: 'Jhenaidah Sadar', slug: 'jhenaidah--jhenaidah-sadar', districtSlug: 'jhenaidah' },
  { name: 'Shailkupa', slug: 'jhenaidah--shailkupa', districtSlug: 'jhenaidah' },
  { name: 'Harinakundu', slug: 'jhenaidah--harinakundu', districtSlug: 'jhenaidah' },
  { name: 'Kaliganj', slug: 'jhenaidah--kaliganj', districtSlug: 'jhenaidah' },
  { name: 'Kotchandpur', slug: 'jhenaidah--kotchandpur', districtSlug: 'jhenaidah' },
  { name: 'Moheshpur', slug: 'jhenaidah--moheshpur', districtSlug: 'jhenaidah' },
  { name: 'Jhalakathi Sadar', slug: 'jhalakathi--jhalakathi-sadar', districtSlug: 'jhalakathi' },
  { name: 'Kathalia', slug: 'jhalakathi--kathalia', districtSlug: 'jhalakathi' },
  { name: 'Nalchity', slug: 'jhalakathi--nalchity', districtSlug: 'jhalakathi' },
  { name: 'Rajapur', slug: 'jhalakathi--rajapur', districtSlug: 'jhalakathi' },
  { name: 'Bauphal', slug: 'patuakhali--bauphal', districtSlug: 'patuakhali' },
  { name: 'Patuakhali Sadar', slug: 'patuakhali--patuakhali-sadar', districtSlug: 'patuakhali' },
  { name: 'Dumki', slug: 'patuakhali--dumki', districtSlug: 'patuakhali' },
  { name: 'Dashmina', slug: 'patuakhali--dashmina', districtSlug: 'patuakhali' },
  { name: 'Kalapara', slug: 'patuakhali--kalapara', districtSlug: 'patuakhali' },
  { name: 'Mirzaganj', slug: 'patuakhali--mirzaganj', districtSlug: 'patuakhali' },
  { name: 'Galachipa', slug: 'patuakhali--galachipa', districtSlug: 'patuakhali' },
  { name: 'Rangabali', slug: 'patuakhali--rangabali', districtSlug: 'patuakhali' },
  { name: 'Pirojpur Sadar', slug: 'pirojpur--pirojpur-sadar', districtSlug: 'pirojpur' },
  { name: 'Nazirpur', slug: 'pirojpur--nazirpur', districtSlug: 'pirojpur' },
  { name: 'Kawkhali', slug: 'pirojpur--kawkhali', districtSlug: 'pirojpur' },
  { name: 'Zianagar', slug: 'pirojpur--zianagar', districtSlug: 'pirojpur' },
  { name: 'Bhandaria', slug: 'pirojpur--bhandaria', districtSlug: 'pirojpur' },
  { name: 'Mathbaria', slug: 'pirojpur--mathbaria', districtSlug: 'pirojpur' },
  { name: 'Nesarabad', slug: 'pirojpur--nesarabad', districtSlug: 'pirojpur' },
  { name: 'Barishal Sadar', slug: 'barishal--barishal-sadar', districtSlug: 'barishal' },
  { name: 'Bakerganj', slug: 'barishal--bakerganj', districtSlug: 'barishal' },
  { name: 'Babuganj', slug: 'barishal--babuganj', districtSlug: 'barishal' },
  { name: 'Wazirpur', slug: 'barishal--wazirpur', districtSlug: 'barishal' },
  { name: 'Banaripara', slug: 'barishal--banaripara', districtSlug: 'barishal' },
  { name: 'Gournadi', slug: 'barishal--gournadi', districtSlug: 'barishal' },
  { name: 'Agailjhara', slug: 'barishal--agailjhara', districtSlug: 'barishal' },
  { name: 'Mehendiganj', slug: 'barishal--mehendiganj', districtSlug: 'barishal' },
  { name: 'Muladi', slug: 'barishal--muladi', districtSlug: 'barishal' },
  { name: 'Hizla', slug: 'barishal--hizla', districtSlug: 'barishal' },
  { name: 'Bhola Sadar', slug: 'bhola--bhola-sadar', districtSlug: 'bhola' },
  { name: 'Borhan Sddin', slug: 'bhola--borhan-sddin', districtSlug: 'bhola' },
  { name: 'Charfesson', slug: 'bhola--charfesson', districtSlug: 'bhola' },
  { name: 'Doulatkhan', slug: 'bhola--doulatkhan', districtSlug: 'bhola' },
  { name: 'Monpura', slug: 'bhola--monpura', districtSlug: 'bhola' },
  { name: 'Tazumuddin', slug: 'bhola--tazumuddin', districtSlug: 'bhola' },
  { name: 'Lalmohan', slug: 'bhola--lalmohan', districtSlug: 'bhola' },
  { name: 'Amtali', slug: 'barguna--amtali', districtSlug: 'barguna' },
  { name: 'Barguna Sadar', slug: 'barguna--barguna-sadar', districtSlug: 'barguna' },
  { name: 'Betagi', slug: 'barguna--betagi', districtSlug: 'barguna' },
  { name: 'Bamna', slug: 'barguna--bamna', districtSlug: 'barguna' },
  { name: 'Pathorghata', slug: 'barguna--pathorghata', districtSlug: 'barguna' },
  { name: 'Taltali', slug: 'barguna--taltali', districtSlug: 'barguna' },
  { name: 'Balaganj', slug: 'sylhet--balaganj', districtSlug: 'sylhet' },
  { name: 'Beanibazar', slug: 'sylhet--beanibazar', districtSlug: 'sylhet' },
  { name: 'Bishwanath', slug: 'sylhet--bishwanath', districtSlug: 'sylhet' },
  { name: 'Companiganj', slug: 'sylhet--companiganj', districtSlug: 'sylhet' },
  { name: 'Fenchuganj', slug: 'sylhet--fenchuganj', districtSlug: 'sylhet' },
  { name: 'Golapganj', slug: 'sylhet--golapganj', districtSlug: 'sylhet' },
  { name: 'Gowainghat', slug: 'sylhet--gowainghat', districtSlug: 'sylhet' },
  { name: 'Jaintiapur', slug: 'sylhet--jaintiapur', districtSlug: 'sylhet' },
  { name: 'Kanaighat', slug: 'sylhet--kanaighat', districtSlug: 'sylhet' },
  { name: 'Sylhet Sadar', slug: 'sylhet--sylhet-sadar', districtSlug: 'sylhet' },
  { name: 'Zakiganj', slug: 'sylhet--zakiganj', districtSlug: 'sylhet' },
  { name: 'Dakshinsurma', slug: 'sylhet--dakshinsurma', districtSlug: 'sylhet' },
  { name: 'Osmaninagar', slug: 'sylhet--osmaninagar', districtSlug: 'sylhet' },
  { name: 'Barlekha', slug: 'moulvibazar--barlekha', districtSlug: 'moulvibazar' },
  { name: 'Kamolganj', slug: 'moulvibazar--kamolganj', districtSlug: 'moulvibazar' },
  { name: 'Kulaura', slug: 'moulvibazar--kulaura', districtSlug: 'moulvibazar' },
  { name: 'Moulvibazar Sadar', slug: 'moulvibazar--moulvibazar-sadar', districtSlug: 'moulvibazar' },
  { name: 'Rajnagar', slug: 'moulvibazar--rajnagar', districtSlug: 'moulvibazar' },
  { name: 'Sreemangal', slug: 'moulvibazar--sreemangal', districtSlug: 'moulvibazar' },
  { name: 'Juri', slug: 'moulvibazar--juri', districtSlug: 'moulvibazar' },
  { name: 'Nabiganj', slug: 'habiganj--nabiganj', districtSlug: 'habiganj' },
  { name: 'Bahubal', slug: 'habiganj--bahubal', districtSlug: 'habiganj' },
  { name: 'Ajmiriganj', slug: 'habiganj--ajmiriganj', districtSlug: 'habiganj' },
  { name: 'Baniachong', slug: 'habiganj--baniachong', districtSlug: 'habiganj' },
  { name: 'Lakhai', slug: 'habiganj--lakhai', districtSlug: 'habiganj' },
  { name: 'Chunarughat', slug: 'habiganj--chunarughat', districtSlug: 'habiganj' },
  { name: 'Habiganj Sadar', slug: 'habiganj--habiganj-sadar', districtSlug: 'habiganj' },
  { name: 'Madhabpur', slug: 'habiganj--madhabpur', districtSlug: 'habiganj' },
  { name: 'Sunamganj Sadar', slug: 'sunamganj--sunamganj-sadar', districtSlug: 'sunamganj' },
  { name: 'South Sunamganj', slug: 'sunamganj--south-sunamganj', districtSlug: 'sunamganj' },
  { name: 'Bishwambarpur', slug: 'sunamganj--bishwambarpur', districtSlug: 'sunamganj' },
  { name: 'Chhatak', slug: 'sunamganj--chhatak', districtSlug: 'sunamganj' },
  { name: 'Jagannathpur', slug: 'sunamganj--jagannathpur', districtSlug: 'sunamganj' },
  { name: 'Dowarabazar', slug: 'sunamganj--dowarabazar', districtSlug: 'sunamganj' },
  { name: 'Tahirpur', slug: 'sunamganj--tahirpur', districtSlug: 'sunamganj' },
  { name: 'Dharmapasha', slug: 'sunamganj--dharmapasha', districtSlug: 'sunamganj' },
  { name: 'Jamalganj', slug: 'sunamganj--jamalganj', districtSlug: 'sunamganj' },
  { name: 'Shalla', slug: 'sunamganj--shalla', districtSlug: 'sunamganj' },
  { name: 'Derai', slug: 'sunamganj--derai', districtSlug: 'sunamganj' },
  { name: 'Belabo', slug: 'narsingdi--belabo', districtSlug: 'narsingdi' },
  { name: 'Monohardi', slug: 'narsingdi--monohardi', districtSlug: 'narsingdi' },
  { name: 'Narsingdi Sadar', slug: 'narsingdi--narsingdi-sadar', districtSlug: 'narsingdi' },
  { name: 'Palash', slug: 'narsingdi--palash', districtSlug: 'narsingdi' },
  { name: 'Raipura', slug: 'narsingdi--raipura', districtSlug: 'narsingdi' },
  { name: 'Shibpur', slug: 'narsingdi--shibpur', districtSlug: 'narsingdi' },
  { name: 'Kaliganj', slug: 'gazipur--kaliganj', districtSlug: 'gazipur' },
  { name: 'Kaliakair', slug: 'gazipur--kaliakair', districtSlug: 'gazipur' },
  { name: 'Kapasia', slug: 'gazipur--kapasia', districtSlug: 'gazipur' },
  { name: 'Gazipur Sadar', slug: 'gazipur--gazipur-sadar', districtSlug: 'gazipur' },
  { name: 'Sreepur', slug: 'gazipur--sreepur', districtSlug: 'gazipur' },
  { name: 'Shariatpur Sadar', slug: 'shariatpur--shariatpur-sadar', districtSlug: 'shariatpur' },
  { name: 'Naria', slug: 'shariatpur--naria', districtSlug: 'shariatpur' },
  { name: 'Zajira', slug: 'shariatpur--zajira', districtSlug: 'shariatpur' },
  { name: 'Gosairhat', slug: 'shariatpur--gosairhat', districtSlug: 'shariatpur' },
  { name: 'Bhedarganj', slug: 'shariatpur--bhedarganj', districtSlug: 'shariatpur' },
  { name: 'Damudya', slug: 'shariatpur--damudya', districtSlug: 'shariatpur' },
  { name: 'Araihazar', slug: 'narayanganj--araihazar', districtSlug: 'narayanganj' },
  { name: 'Bandar', slug: 'narayanganj--bandar', districtSlug: 'narayanganj' },
  { name: 'Narayanganj Sadar', slug: 'narayanganj--narayanganj-sadar', districtSlug: 'narayanganj' },
  { name: 'Rupganj', slug: 'narayanganj--rupganj', districtSlug: 'narayanganj' },
  { name: 'Sonargaon', slug: 'narayanganj--sonargaon', districtSlug: 'narayanganj' },
  { name: 'Basail', slug: 'tangail--basail', districtSlug: 'tangail' },
  { name: 'Bhuapur', slug: 'tangail--bhuapur', districtSlug: 'tangail' },
  { name: 'Delduar', slug: 'tangail--delduar', districtSlug: 'tangail' },
  { name: 'Ghatail', slug: 'tangail--ghatail', districtSlug: 'tangail' },
  { name: 'Gopalpur', slug: 'tangail--gopalpur', districtSlug: 'tangail' },
  { name: 'Madhupur', slug: 'tangail--madhupur', districtSlug: 'tangail' },
  { name: 'Mirzapur', slug: 'tangail--mirzapur', districtSlug: 'tangail' },
  { name: 'Nagarpur', slug: 'tangail--nagarpur', districtSlug: 'tangail' },
  { name: 'Sakhipur', slug: 'tangail--sakhipur', districtSlug: 'tangail' },
  { name: 'Tangail Sadar', slug: 'tangail--tangail-sadar', districtSlug: 'tangail' },
  { name: 'Kalihati', slug: 'tangail--kalihati', districtSlug: 'tangail' },
  { name: 'Dhanbari', slug: 'tangail--dhanbari', districtSlug: 'tangail' },
  { name: 'Itna', slug: 'kishoreganj--itna', districtSlug: 'kishoreganj' },
  { name: 'Katiadi', slug: 'kishoreganj--katiadi', districtSlug: 'kishoreganj' },
  { name: 'Bhairab', slug: 'kishoreganj--bhairab', districtSlug: 'kishoreganj' },
  { name: 'Tarail', slug: 'kishoreganj--tarail', districtSlug: 'kishoreganj' },
  { name: 'Hossainpur', slug: 'kishoreganj--hossainpur', districtSlug: 'kishoreganj' },
  { name: 'Pakundia', slug: 'kishoreganj--pakundia', districtSlug: 'kishoreganj' },
  { name: 'Kuliarchar', slug: 'kishoreganj--kuliarchar', districtSlug: 'kishoreganj' },
  { name: 'Kishoreganj Sadar', slug: 'kishoreganj--kishoreganj-sadar', districtSlug: 'kishoreganj' },
  { name: 'Karimgonj', slug: 'kishoreganj--karimgonj', districtSlug: 'kishoreganj' },
  { name: 'Bajitpur', slug: 'kishoreganj--bajitpur', districtSlug: 'kishoreganj' },
  { name: 'Austagram', slug: 'kishoreganj--austagram', districtSlug: 'kishoreganj' },
  { name: 'Mithamoin', slug: 'kishoreganj--mithamoin', districtSlug: 'kishoreganj' },
  { name: 'Nikli', slug: 'kishoreganj--nikli', districtSlug: 'kishoreganj' },
  { name: 'Harirampur', slug: 'manikganj--harirampur', districtSlug: 'manikganj' },
  { name: 'Saturia', slug: 'manikganj--saturia', districtSlug: 'manikganj' },
  { name: 'Manikganj Sadar', slug: 'manikganj--manikganj-sadar', districtSlug: 'manikganj' },
  { name: 'Gior', slug: 'manikganj--gior', districtSlug: 'manikganj' },
  { name: 'Shibaloy', slug: 'manikganj--shibaloy', districtSlug: 'manikganj' },
  { name: 'Doulatpur', slug: 'manikganj--doulatpur', districtSlug: 'manikganj' },
  { name: 'Singiar', slug: 'manikganj--singiar', districtSlug: 'manikganj' },
  // Not from the source dataset — see the "Dhaka City" note in this file's
  // module doc comment. Represents Dhaka North + South City Corporation,
  // which the upazila-level source has no entry for at all.
  { name: 'Dhaka City', slug: 'dhaka--dhaka-city', districtSlug: 'dhaka' },
  { name: 'Savar', slug: 'dhaka--savar', districtSlug: 'dhaka' },
  { name: 'Dhamrai', slug: 'dhaka--dhamrai', districtSlug: 'dhaka' },
  { name: 'Keraniganj', slug: 'dhaka--keraniganj', districtSlug: 'dhaka' },
  { name: 'Nawabganj', slug: 'dhaka--nawabganj', districtSlug: 'dhaka' },
  { name: 'Dohar', slug: 'dhaka--dohar', districtSlug: 'dhaka' },
  { name: 'Munshiganj Sadar', slug: 'munshiganj--munshiganj-sadar', districtSlug: 'munshiganj' },
  { name: 'Sreenagar', slug: 'munshiganj--sreenagar', districtSlug: 'munshiganj' },
  { name: 'Sirajdikhan', slug: 'munshiganj--sirajdikhan', districtSlug: 'munshiganj' },
  { name: 'Louhajanj', slug: 'munshiganj--louhajanj', districtSlug: 'munshiganj' },
  { name: 'Gajaria', slug: 'munshiganj--gajaria', districtSlug: 'munshiganj' },
  { name: 'Tongibari', slug: 'munshiganj--tongibari', districtSlug: 'munshiganj' },
  { name: 'Rajbari Sadar', slug: 'rajbari--rajbari-sadar', districtSlug: 'rajbari' },
  { name: 'Goalanda', slug: 'rajbari--goalanda', districtSlug: 'rajbari' },
  { name: 'Pangsa', slug: 'rajbari--pangsa', districtSlug: 'rajbari' },
  { name: 'Baliakandi', slug: 'rajbari--baliakandi', districtSlug: 'rajbari' },
  { name: 'Kalukhali', slug: 'rajbari--kalukhali', districtSlug: 'rajbari' },
  { name: 'Madaripur Sadar', slug: 'madaripur--madaripur-sadar', districtSlug: 'madaripur' },
  { name: 'Shibchar', slug: 'madaripur--shibchar', districtSlug: 'madaripur' },
  { name: 'Kalkini', slug: 'madaripur--kalkini', districtSlug: 'madaripur' },
  { name: 'Rajoir', slug: 'madaripur--rajoir', districtSlug: 'madaripur' },
  { name: 'Gopalganj Sadar', slug: 'gopalganj--gopalganj-sadar', districtSlug: 'gopalganj' },
  { name: 'Kashiani', slug: 'gopalganj--kashiani', districtSlug: 'gopalganj' },
  { name: 'Tungipara', slug: 'gopalganj--tungipara', districtSlug: 'gopalganj' },
  { name: 'Kotalipara', slug: 'gopalganj--kotalipara', districtSlug: 'gopalganj' },
  { name: 'Muksudpur', slug: 'gopalganj--muksudpur', districtSlug: 'gopalganj' },
  { name: 'Faridpur Sadar', slug: 'faridpur--faridpur-sadar', districtSlug: 'faridpur' },
  { name: 'Alfadanga', slug: 'faridpur--alfadanga', districtSlug: 'faridpur' },
  { name: 'Boalmari', slug: 'faridpur--boalmari', districtSlug: 'faridpur' },
  { name: 'Sadarpur', slug: 'faridpur--sadarpur', districtSlug: 'faridpur' },
  { name: 'Nagarkanda', slug: 'faridpur--nagarkanda', districtSlug: 'faridpur' },
  { name: 'Bhanga', slug: 'faridpur--bhanga', districtSlug: 'faridpur' },
  { name: 'Charbhadrasan', slug: 'faridpur--charbhadrasan', districtSlug: 'faridpur' },
  { name: 'Madhukhali', slug: 'faridpur--madhukhali', districtSlug: 'faridpur' },
  { name: 'Saltha', slug: 'faridpur--saltha', districtSlug: 'faridpur' },
  { name: 'Panchagarh Sadar', slug: 'panchagarh--panchagarh-sadar', districtSlug: 'panchagarh' },
  { name: 'Debiganj', slug: 'panchagarh--debiganj', districtSlug: 'panchagarh' },
  { name: 'Boda', slug: 'panchagarh--boda', districtSlug: 'panchagarh' },
  { name: 'Atwari', slug: 'panchagarh--atwari', districtSlug: 'panchagarh' },
  { name: 'Tetulia', slug: 'panchagarh--tetulia', districtSlug: 'panchagarh' },
  { name: 'Nawabganj', slug: 'dinajpur--nawabganj', districtSlug: 'dinajpur' },
  { name: 'Birganj', slug: 'dinajpur--birganj', districtSlug: 'dinajpur' },
  { name: 'Ghoraghat', slug: 'dinajpur--ghoraghat', districtSlug: 'dinajpur' },
  { name: 'Birampur', slug: 'dinajpur--birampur', districtSlug: 'dinajpur' },
  { name: 'Parbatipur', slug: 'dinajpur--parbatipur', districtSlug: 'dinajpur' },
  { name: 'Bochaganj', slug: 'dinajpur--bochaganj', districtSlug: 'dinajpur' },
  { name: 'Kaharol', slug: 'dinajpur--kaharol', districtSlug: 'dinajpur' },
  { name: 'Fulbari', slug: 'dinajpur--fulbari', districtSlug: 'dinajpur' },
  { name: 'Dinajpur Sadar', slug: 'dinajpur--dinajpur-sadar', districtSlug: 'dinajpur' },
  { name: 'Hakimpur', slug: 'dinajpur--hakimpur', districtSlug: 'dinajpur' },
  { name: 'Khansama', slug: 'dinajpur--khansama', districtSlug: 'dinajpur' },
  { name: 'Birol', slug: 'dinajpur--birol', districtSlug: 'dinajpur' },
  { name: 'Chirirbandar', slug: 'dinajpur--chirirbandar', districtSlug: 'dinajpur' },
  { name: 'Lalmonirhat Sadar', slug: 'lalmonirhat--lalmonirhat-sadar', districtSlug: 'lalmonirhat' },
  { name: 'Kaliganj', slug: 'lalmonirhat--kaliganj', districtSlug: 'lalmonirhat' },
  { name: 'Hatibandha', slug: 'lalmonirhat--hatibandha', districtSlug: 'lalmonirhat' },
  { name: 'Patgram', slug: 'lalmonirhat--patgram', districtSlug: 'lalmonirhat' },
  { name: 'Aditmari', slug: 'lalmonirhat--aditmari', districtSlug: 'lalmonirhat' },
  { name: 'Syedpur', slug: 'nilphamari--syedpur', districtSlug: 'nilphamari' },
  { name: 'Domar', slug: 'nilphamari--domar', districtSlug: 'nilphamari' },
  { name: 'Dimla', slug: 'nilphamari--dimla', districtSlug: 'nilphamari' },
  { name: 'Jaldhaka', slug: 'nilphamari--jaldhaka', districtSlug: 'nilphamari' },
  { name: 'Kishorganj', slug: 'nilphamari--kishorganj', districtSlug: 'nilphamari' },
  { name: 'Nilphamari Sadar', slug: 'nilphamari--nilphamari-sadar', districtSlug: 'nilphamari' },
  { name: 'Sadullapur', slug: 'gaibandha--sadullapur', districtSlug: 'gaibandha' },
  { name: 'Gaibandha Sadar', slug: 'gaibandha--gaibandha-sadar', districtSlug: 'gaibandha' },
  { name: 'Palashbari', slug: 'gaibandha--palashbari', districtSlug: 'gaibandha' },
  { name: 'Saghata', slug: 'gaibandha--saghata', districtSlug: 'gaibandha' },
  { name: 'Gobindaganj', slug: 'gaibandha--gobindaganj', districtSlug: 'gaibandha' },
  { name: 'Sundarganj', slug: 'gaibandha--sundarganj', districtSlug: 'gaibandha' },
  { name: 'Phulchari', slug: 'gaibandha--phulchari', districtSlug: 'gaibandha' },
  { name: 'Thakurgaon Sadar', slug: 'thakurgaon--thakurgaon-sadar', districtSlug: 'thakurgaon' },
  { name: 'Pirganj', slug: 'thakurgaon--pirganj', districtSlug: 'thakurgaon' },
  { name: 'Ranisankail', slug: 'thakurgaon--ranisankail', districtSlug: 'thakurgaon' },
  { name: 'Haripur', slug: 'thakurgaon--haripur', districtSlug: 'thakurgaon' },
  { name: 'Baliadangi', slug: 'thakurgaon--baliadangi', districtSlug: 'thakurgaon' },
  { name: 'Rangpur Sadar', slug: 'rangpur--rangpur-sadar', districtSlug: 'rangpur' },
  { name: 'Gangachara', slug: 'rangpur--gangachara', districtSlug: 'rangpur' },
  { name: 'Taragonj', slug: 'rangpur--taragonj', districtSlug: 'rangpur' },
  { name: 'Badargonj', slug: 'rangpur--badargonj', districtSlug: 'rangpur' },
  { name: 'Mithapukur', slug: 'rangpur--mithapukur', districtSlug: 'rangpur' },
  { name: 'Pirgonj', slug: 'rangpur--pirgonj', districtSlug: 'rangpur' },
  { name: 'Kaunia', slug: 'rangpur--kaunia', districtSlug: 'rangpur' },
  { name: 'Pirgacha', slug: 'rangpur--pirgacha', districtSlug: 'rangpur' },
  { name: 'Kurigram Sadar', slug: 'kurigram--kurigram-sadar', districtSlug: 'kurigram' },
  { name: 'Nageshwari', slug: 'kurigram--nageshwari', districtSlug: 'kurigram' },
  { name: 'Bhurungamari', slug: 'kurigram--bhurungamari', districtSlug: 'kurigram' },
  { name: 'Phulbari', slug: 'kurigram--phulbari', districtSlug: 'kurigram' },
  { name: 'Rajarhat', slug: 'kurigram--rajarhat', districtSlug: 'kurigram' },
  { name: 'Ulipur', slug: 'kurigram--ulipur', districtSlug: 'kurigram' },
  { name: 'Chilmari', slug: 'kurigram--chilmari', districtSlug: 'kurigram' },
  { name: 'Rowmari', slug: 'kurigram--rowmari', districtSlug: 'kurigram' },
  { name: 'Charrajibpur', slug: 'kurigram--charrajibpur', districtSlug: 'kurigram' },
  { name: 'Sherpur Sadar', slug: 'sherpur--sherpur-sadar', districtSlug: 'sherpur' },
  { name: 'Nalitabari', slug: 'sherpur--nalitabari', districtSlug: 'sherpur' },
  { name: 'Sreebordi', slug: 'sherpur--sreebordi', districtSlug: 'sherpur' },
  { name: 'Nokla', slug: 'sherpur--nokla', districtSlug: 'sherpur' },
  { name: 'Jhenaigati', slug: 'sherpur--jhenaigati', districtSlug: 'sherpur' },
  { name: 'Fulbaria', slug: 'mymensingh--fulbaria', districtSlug: 'mymensingh' },
  { name: 'Trishal', slug: 'mymensingh--trishal', districtSlug: 'mymensingh' },
  { name: 'Bhaluka', slug: 'mymensingh--bhaluka', districtSlug: 'mymensingh' },
  { name: 'Muktagacha', slug: 'mymensingh--muktagacha', districtSlug: 'mymensingh' },
  { name: 'Mymensingh Sadar', slug: 'mymensingh--mymensingh-sadar', districtSlug: 'mymensingh' },
  { name: 'Dhobaura', slug: 'mymensingh--dhobaura', districtSlug: 'mymensingh' },
  { name: 'Phulpur', slug: 'mymensingh--phulpur', districtSlug: 'mymensingh' },
  { name: 'Haluaghat', slug: 'mymensingh--haluaghat', districtSlug: 'mymensingh' },
  { name: 'Gouripur', slug: 'mymensingh--gouripur', districtSlug: 'mymensingh' },
  { name: 'Gafargaon', slug: 'mymensingh--gafargaon', districtSlug: 'mymensingh' },
  { name: 'Iswarganj', slug: 'mymensingh--iswarganj', districtSlug: 'mymensingh' },
  { name: 'Nandail', slug: 'mymensingh--nandail', districtSlug: 'mymensingh' },
  { name: 'Tarakanda', slug: 'mymensingh--tarakanda', districtSlug: 'mymensingh' },
  { name: 'Jamalpur Sadar', slug: 'jamalpur--jamalpur-sadar', districtSlug: 'jamalpur' },
  { name: 'Melandah', slug: 'jamalpur--melandah', districtSlug: 'jamalpur' },
  { name: 'Islampur', slug: 'jamalpur--islampur', districtSlug: 'jamalpur' },
  { name: 'Dewangonj', slug: 'jamalpur--dewangonj', districtSlug: 'jamalpur' },
  { name: 'Sarishabari', slug: 'jamalpur--sarishabari', districtSlug: 'jamalpur' },
  { name: 'Madarganj', slug: 'jamalpur--madarganj', districtSlug: 'jamalpur' },
  { name: 'Bokshiganj', slug: 'jamalpur--bokshiganj', districtSlug: 'jamalpur' },
  { name: 'Barhatta', slug: 'netrokona--barhatta', districtSlug: 'netrokona' },
  { name: 'Durgapur', slug: 'netrokona--durgapur', districtSlug: 'netrokona' },
  { name: 'Kendua', slug: 'netrokona--kendua', districtSlug: 'netrokona' },
  { name: 'Atpara', slug: 'netrokona--atpara', districtSlug: 'netrokona' },
  { name: 'Madan', slug: 'netrokona--madan', districtSlug: 'netrokona' },
  { name: 'Khaliajuri', slug: 'netrokona--khaliajuri', districtSlug: 'netrokona' },
  { name: 'Kalmakanda', slug: 'netrokona--kalmakanda', districtSlug: 'netrokona' },
  { name: 'Mohongonj', slug: 'netrokona--mohongonj', districtSlug: 'netrokona' },
  { name: 'Purbadhala', slug: 'netrokona--purbadhala', districtSlug: 'netrokona' },
  { name: 'Netrokona Sadar', slug: 'netrokona--netrokona-sadar', districtSlug: 'netrokona' },
  { name: 'Eidgaon', slug: 'coxs-bazar--eidgaon', districtSlug: 'coxs-bazar' },
  { name: 'Madhyanagar', slug: 'sunamganj--madhyanagar', districtSlug: 'sunamganj' },
  { name: 'Dasar', slug: 'madaripur--dasar', districtSlug: 'madaripur' },
];

/** Display names only -- what `Order.shippingAddress.division` stores and validates against. */
export const DIVISION_NAMES: readonly string[] = DIVISIONS.map((division) => division.name);

/** Districts belonging to a division, by division *name* -- what the dependent select and the server both call with. */
export function districtsForDivision(divisionName: string): District[] {
  const division = DIVISIONS.find((entry) => entry.name === divisionName);
  if (!division) return [];
  return DISTRICTS.filter((district) => district.divisionSlug === division.slug);
}

/** Upazilas belonging to a district, by district *name*. */
export function upazilasForDistrict(districtName: string): Upazila[] {
  const district = DISTRICTS.find((entry) => entry.name === districtName);
  if (!district) return [];
  return UPAZILAS.filter((upazila) => upazila.districtSlug === district.slug);
}

/**
 * Whether a division -> district -> upazila combination is a real, correctly
 * nested one -- the server-side half of the dependent-select guarantee
 * (section 6).
 *
 * Each level is checked against its *actual parent*, not merely checked to
 * exist: a well-formed-looking but mismatched submission -- a real district
 * paired with the wrong division, or a real upazila paired with the wrong
 * district -- is rejected exactly like an unknown name would be.
 */
export function isValidLocationHierarchy(
  divisionName: string,
  districtName: string,
  upazilaName: string,
): boolean {
  const division = DIVISIONS.find((entry) => entry.name === divisionName);
  if (!division) return false;

  const district = DISTRICTS.find(
    (entry) => entry.name === districtName && entry.divisionSlug === division.slug,
  );
  if (!district) return false;

  return UPAZILAS.some((entry) => entry.name === upazilaName && entry.districtSlug === district.slug);
}
