'use client';

import { Button, FieldError, Input, Label, Modal, Spinner, TextField, useOverlayState } from '@heroui/react';
import { useState, type FormEvent } from 'react';
import { formatTaka } from '@/lib/catalogue/price';
import { AddressFields, type AddressValues } from '@/components/checkout/AddressFields';
import { resolveDeliveryCharge } from '@/lib/checkout/delivery';
import { checkoutErrorMessage } from '@/lib/checkout/validation';
import { useOrderSubmission } from '@/lib/checkout/useOrderSubmission';

/**
 * One-click COD / express order — design direction, §16.
 *
 * "Buy Now" on a product page opens this instead of routing through cart and
 * checkout. It is not a second order system: it collects the same fields and
 * calls the same `/api/orders` endpoint `CheckoutForm` does
 * (`useOrderSubmission`), just for a single product chosen up front (§3
 * "prefer the simpler architecture that does not duplicate pricing/order
 * logic") — and prices delivery with the exact same `resolveDeliveryCharge()`
 * `CheckoutForm` previews with, so the two surfaces can never show a
 * different fee for the same address (§6).
 *
 * `idempotencyKey` is generated by the caller at the moment it opens the
 * modal (see `PurchaseControls`), not here — closing without ordering and
 * reopening (this product, or after navigating, another) must never risk
 * resolving to a stale earlier attempt (§12).
 */

const emptyAddress: AddressValues = { division: '', district: '', upazila: '', street: '' };

export function ExpressCodModal({
  state,
  product,
  quantity,
  idempotencyKey,
}: {
  state: ReturnType<typeof useOverlayState>;
  product: { slug: string; name: string; priceMinor: number; imageUrl?: string; imageAlt?: string; isDemo?: boolean };
  quantity: number;
  idempotencyKey: string;
}) {
  const { submit, submitting, fieldErrors, formError } = useOrderSubmission();
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState<AddressValues>(emptyAddress);

  const hasValidLocation = address.division !== '' && address.district !== '' && address.upazila !== '';
  const deliveryChargeMinor = hasValidLocation
    ? resolveDeliveryCharge(address.district, address.upazila)
    : undefined;

  const subtotalMinor = product.priceMinor * quantity;
  const totalMinor = deliveryChargeMinor !== undefined ? subtotalMinor + deliveryChargeMinor : undefined;

  const canSubmit = name.trim() !== '' && phone.trim() !== '' && hasValidLocation && address.street.trim() !== '';

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!canSubmit) return;
    await submit({
      customer: { name, phone },
      shippingAddress: address,
      items: [{ slug: product.slug, quantity }],
      idempotencyKey,
    });
  }

  return (
    <Modal state={state}>
      <Modal.Backdrop>
        <Modal.Container size="md" placement="center">
          <Modal.Dialog>
            <Modal.Header>
              <Modal.Heading>Order with Cash on Delivery</Modal.Heading>
            </Modal.Header>
            <Modal.Body>
              <form id="express-cod-form" onSubmit={handleSubmit} noValidate className="space-y-5">
                <div className="rounded-xl border border-line bg-surface-2 p-3.5">
                  <p className="text-sm font-semibold text-ink">{product.name}</p>
                  <p className="mt-1 text-sm text-ink-muted">
                    Qty {quantity} · <span className="latin font-semibold text-ink">{formatTaka(subtotalMinor)}</span>
                  </p>
                  <dl className="mt-2 space-y-1 border-t border-line pt-2 text-sm">
                    <div className="flex items-center justify-between">
                      <dt className="text-ink-muted">Delivery</dt>
                      <dd className={deliveryChargeMinor === undefined ? 'text-ink-muted' : 'latin font-medium text-ink'}>
                        {deliveryChargeMinor === undefined ? 'Select your delivery location' : formatTaka(deliveryChargeMinor)}
                      </dd>
                    </div>
                    {totalMinor !== undefined ? (
                      <div className="flex items-center justify-between font-semibold text-ink">
                        <dt>Total (COD)</dt>
                        <dd className="latin">{formatTaka(totalMinor)}</dd>
                      </div>
                    ) : null}
                  </dl>
                </div>

                {formError ? (
                  <p role="alert" className="text-sm text-danger">
                    {formError}
                  </p>
                ) : null}

                <TextField
                  name="name"
                  value={name}
                  onChange={setName}
                  isRequired
                  isInvalid={Boolean(fieldErrors['customer.name'])}
                  autoComplete="name"
                  className="w-full"
                >
                  <Label>Your name</Label>
                  <Input placeholder="Your full name" />
                  {fieldErrors['customer.name'] ? (
                    <FieldError>{checkoutErrorMessage(fieldErrors['customer.name'])}</FieldError>
                  ) : null}
                </TextField>

                <TextField
                  name="phone"
                  type="tel"
                  value={phone}
                  onChange={setPhone}
                  isRequired
                  isInvalid={Boolean(fieldErrors['customer.phone'])}
                  autoComplete="tel"
                  className="w-full"
                >
                  <Label>Phone number</Label>
                  <Input inputMode="tel" placeholder="01XXXXXXXXX" className="latin" />
                  {fieldErrors['customer.phone'] ? (
                    <FieldError>{checkoutErrorMessage(fieldErrors['customer.phone'])}</FieldError>
                  ) : null}
                </TextField>

                <AddressFields
                  idPrefix="express"
                  values={address}
                  onChange={setAddress}
                  errors={{
                    division: fieldErrors['shippingAddress.division'],
                    district: fieldErrors['shippingAddress.district'],
                    upazila: fieldErrors['shippingAddress.upazila'],
                    street: fieldErrors['shippingAddress.street'],
                  }}
                />
              </form>
            </Modal.Body>
            <Modal.Footer>
              <Button variant="outline" isDisabled={submitting} onPress={state.close}>
                Cancel
              </Button>
              <Button type="submit" form="express-cod-form" variant="primary" isDisabled={submitting || !canSubmit}>
                {submitting ? (
                  <span className="inline-flex items-center gap-2">
                    <Spinner size="sm" aria-hidden="true" />
                    Placing order…
                  </span>
                ) : (
                  'Place order'
                )}
              </Button>
            </Modal.Footer>
          </Modal.Dialog>
        </Modal.Container>
      </Modal.Backdrop>
    </Modal>
  );
}
