import type { Metadata } from 'next';
import { CatalogueEmptyState } from '@/components/commerce/CatalogueEmptyState';
import { ProductGrid } from '@/components/commerce/ProductGrid';
import { Container } from '@/components/ui/Container';
import {
  DEFAULT_SORT,
  normaliseSearchInput,
  parseSearchTerms,
  type RawSearchParams,
} from '@/lib/catalogue/discovery';
import { getCatalogue } from '@/lib/content/storefront';
import { buildMetadata } from '@/lib/seo/metadata';

/**
 * Search results — `/search?q=…`.
 *
 * The header field is a plain `GET` form pointing here, which is why searching
 * has always worked the moment this route existed: no client state, no fetch, no
 * autocomplete engine. A query is a URL, so it is shareable, refreshable and
 * server-rendered.
 *
 * **No filter or sort controls.** A search over eleven products returns a
 * handful of results; offering to filter and sort them is UI that cannot earn
 * its place (§21). The default ordering — sellable first — is applied.
 *
 * Deliberately not implemented: autocomplete. Phase 3 lists it as optional, and
 * a suggestions dropdown means a client component, a debounce, an endpoint and a
 * per-keystroke round trip to search eleven rows. The results page is fast
 * enough that the dropdown would be the slower path.
 */
export const dynamic = 'force-dynamic';

type PageProps = { searchParams: Promise<RawSearchParams> };

const rawQuery = (params: RawSearchParams): string | undefined =>
  Array.isArray(params.q) ? params.q[0] : params.q;

export async function generateMetadata({ searchParams }: PageProps): Promise<Metadata> {
  const query = normaliseSearchInput(rawQuery(await searchParams));

  /**
   * **Always `noindex`, and always canonical to the bare `/search`.**
   *
   * A results URL is generated by a customer, not authored by anyone. Letting
   * crawlers index one page per query is the classic thin-content trap, and the
   * query itself is user input that must never be reflected into a canonical.
   */
  return buildMetadata({
    path: '/search',
    title: query ? `Search: ${query}` : 'Search products',
    description: 'Search the Renvura catalogue.',
    noindex: true,
  });
}

export default async function SearchPage({ searchParams }: PageProps) {
  const params = await searchParams;
  const query = normaliseSearchInput(rawQuery(params));
  const terms = parseSearchTerms(rawQuery(params));

  const { products, total } =
    terms.length > 0
      ? await getCatalogue({ sort: DEFAULT_SORT, terms })
      : { products: [], total: 0 };

  return (
    <div className="py-10 sm:py-14">
      <Container>
        <header className="max-w-2xl">
          <p className="text-[0.6875rem] font-semibold uppercase tracking-[0.16em] text-ink-muted sm:text-xs">
            Search
          </p>
          <h1 className="mt-2 font-display text-[1.875rem] leading-[1.15] text-ink sm:text-[2.5rem]">
            {query ? (
              <>
                Results for <span className="text-brand-navy">“{query}”</span>
              </>
            ) : (
              'Search products'
            )}
          </h1>

          {terms.length > 0 ? (
            <p aria-live="polite" className="mt-3 text-sm text-ink-muted">
              {total === 1 ? '1 product found' : `${total} products found`}
            </p>
          ) : null}
        </header>

        {/* The field is repeated on the page rather than sending the customer
            back to the header: refining a search is the most likely next
            action, and the header field is not visible on a phone. */}
        <SearchForm defaultValue={query} />

        <div className="mt-8 sm:mt-10">
          {products.length > 0 ? (
            <ProductGrid products={products} aria-label="Search results" />
          ) : terms.length > 0 ? (
            <CatalogueEmptyState
              title={`Nothing matched “${query}”.`}
              body="Try a shorter or more general word — a product name, a material like “wooden”, or a shelf like “math”. The whole catalogue is small enough to browse in a minute."
              bodyBn="আরও সহজ বা ছোট শব্দ দিয়ে খুঁজে দেখুন। পুরো তালিকাটি ছোট, এক নজরেই দেখে নেওয়া যায়।"
              actions={[
                { label: 'View all products', href: '/products', primary: true },
                { label: 'Ask us directly', href: '/contact' },
              ]}
            />
          ) : (
            <CatalogueEmptyState
              title="What are you looking for?"
              body="Search by product name, or by a word that describes it — “wooden”, “beads”, “puzzle”, “math”. You can also browse the whole catalogue."
              actions={[{ label: 'View all products', href: '/products', primary: true }]}
            />
          )}
        </div>
      </Container>
    </div>
  );
}

/** A plain GET form. No JavaScript, no state, works everywhere. */
function SearchForm({ defaultValue }: { defaultValue: string }) {
  return (
    <form action="/search" method="get" role="search" className="mt-6 max-w-xl">
      <label htmlFor="search-page-q" className="sr-only">
        Search products
      </label>
      <div className="flex gap-2">
        <input
          id="search-page-q"
          type="search"
          name="q"
          defaultValue={defaultValue}
          placeholder="Search products…"
          autoComplete="off"
          className="min-h-12 w-full min-w-0 rounded-xl border border-line bg-surface px-4 text-sm text-ink outline-none placeholder:text-ink-muted"
        />
        <button
          type="submit"
          className="min-h-12 shrink-0 rounded-xl bg-accent px-5 text-sm font-semibold text-on-accent transition-opacity hover:opacity-90"
        >
          Search
        </button>
      </div>
    </form>
  );
}
